// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJWtmg0QmWrGJ6CBqwXGP8msxEJgkI0y8',
    appId: '1:76458706086:web:bf3daca6162b5a1703e067',
    messagingSenderId: '76458706086',
    projectId: 'fooddelivery-915cf',
    authDomain: 'fooddelivery-915cf.firebaseapp.com',
    storageBucket: 'fooddelivery-915cf.firebasestorage.app',
    measurementId: 'G-ET6TYE0M78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWm3oLCW1W0RWafGaorcBNSySEVb9xM4',
    appId: '1:76458706086:android:7cbf29e9445a4f9c03e067',
    messagingSenderId: '76458706086',
    projectId: 'fooddelivery-915cf',
    storageBucket: 'fooddelivery-915cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFE0MyEB7zP9ovVECfJL9T78ZySqcn44',
    appId: '1:76458706086:ios:8454098ba0edbc8f03e067',
    messagingSenderId: '76458706086',
    projectId: 'fooddelivery-915cf',
    storageBucket: 'fooddelivery-915cf.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFE0MyEB7zP9ovVECfJL9T78ZySqcn44',
    appId: '1:76458706086:ios:8454098ba0edbc8f03e067',
    messagingSenderId: '76458706086',
    projectId: 'fooddelivery-915cf',
    storageBucket: 'fooddelivery-915cf.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJWtmg0QmWrGJ6CBqwXGP8msxEJgkI0y8',
    appId: '1:76458706086:web:fcd3aa2b27b4d38403e067',
    messagingSenderId: '76458706086',
    projectId: 'fooddelivery-915cf',
    authDomain: 'fooddelivery-915cf.firebaseapp.com',
    storageBucket: 'fooddelivery-915cf.firebasestorage.app',
    measurementId: 'G-0YDVVFZS1K',
  );

}